import type { NativeCursorType } from "@/native/contracts";

/**
 * A single themed cursor image override for one {@link NativeCursorType}.
 *
 * width/height/hotspot are in the same ~32-logical-pixel reference as the built-in
 * PRETTY_NATIVE_CURSOR_ASSETS, so a theme asset matches the default cursor's on-screen
 * size regardless of source PNG resolution. The PNG can be higher-res (e.g. 128x128)
 * and is downscaled at draw time for crisper retina output.
 */
export interface CursorThemeAsset {
	/** Path relative to the public asset root, e.g. "cursors/<id>/arrow.png". */
	assetPath: string;
	width: number;
	height: number;
	hotspotX: number;
	hotspotY: number;
}

export interface CursorTheme {
	id: string;
	/** Display label. Proper nouns, so not run through i18n. */
	name: string;
	/** Attribution / origin for the artwork. */
	source?: string;
	/**
	 * Per-cursor-type overrides. Missing types fall back to the built-in default art,
	 * so a pack that only ships "arrow" and "pointer" is complete.
	 */
	assets: Partial<Record<NativeCursorType, CursorThemeAsset>>;
}

/** Sentinel id for the built-in cursor art (no theme override). */
export const DEFAULT_CURSOR_THEME_ID = "default";

/**
 * One sprite as the native compositor consumes it: a path under the public asset root,
 * plus the hotspot as a 0..1 fraction OF THAT IMAGE.
 *
 * The fraction is the whole point of the contract. The compositor scales the sprite to
 * the cursor-size setting, so an offset expressed in the source image's pixels would have
 * to be rescaled at draw time; a fraction survives any scale untouched. Getting this wrong
 * is what made an enlarged cursor drift further and further from what it points at.
 */
export interface CursorSprite {
	/** Path relative to the public asset root, e.g. "cursors/default/arrow.png". */
	assetPath: string;
	/** Hotspot as a fraction of the image width / height. */
	hotspotX: number;
	hotspotY: number;
}

/**
 * The built-in cursor art, rasterized from src/assets/cursors/*.svg — the native
 * compositor decodes png/jpeg from disk and cannot read those SVGs (they only exist as
 * bundler URLs in the renderer).
 *
 * Generated by scripts/generate-default-cursor-sprites.mjs; regenerate it rather than
 * hand-editing, so the PNGs and these hotspots can't drift apart.
 */
export const DEFAULT_CURSOR_SPRITES: Record<NativeCursorType, CursorSprite> = {
	arrow: { assetPath: "cursors/default/arrow.png", hotspotX: 0.119, hotspotY: 0.0874 },
	text: { assetPath: "cursors/default/text.png", hotspotX: 0.4375, hotspotY: 0.5333 },
	pointer: { assetPath: "cursors/default/pointer.png", hotspotX: 0.3893, hotspotY: 0.0032 },
	crosshair: { assetPath: "cursors/default/crosshair.png", hotspotX: 0.4667, hotspotY: 0.4667 },
	"open-hand": { assetPath: "cursors/default/open-hand.png", hotspotX: 0.4375, hotspotY: 0.1781 },
	"closed-hand": {
		assetPath: "cursors/default/closed-hand.png",
		hotspotX: 0.3889,
		hotspotY: 0.451,
	},
	"resize-ew": { assetPath: "cursors/default/resize-ew.png", hotspotX: 0.4881, hotspotY: 0.4706 },
	"resize-ns": { assetPath: "cursors/default/resize-ns.png", hotspotX: 0.5, hotspotY: 0.5 },
	"resize-nesw": { assetPath: "cursors/default/resize-nesw.png", hotspotX: 0.5, hotspotY: 0.5 },
	"resize-nwse": { assetPath: "cursors/default/resize-nwse.png", hotspotX: 0.5, hotspotY: 0.5 },
	move: { assetPath: "cursors/default/move.png", hotspotX: 0.4444, hotspotY: 0.4444 },
	"not-allowed": { assetPath: "cursors/default/not-allowed.png", hotspotX: 0.5, hotspotY: 0.5 },
	wait: { assetPath: "cursors/default/wait.png", hotspotX: 0.5, hotspotY: 0.5 },
	"app-starting": {
		assetPath: "cursors/default/app-starting.png",
		hotspotX: 0.05,
		hotspotY: 0.0537,
	},
	help: { assetPath: "cursors/default/help.png", hotspotX: 0.0515, hotspotY: 0.0572 },
	"up-arrow": { assetPath: "cursors/default/up-arrow.png", hotspotX: 0.5, hotspotY: 0.069 },
};

/**
 * Bundled cursor themes. Empty on purpose: every pack this list used to carry came from
 * sweezy-cursors.com, whose terms allow personal, non-commercial use and forbid
 * redistributing or repackaging the packs without written permission. Most of them also
 * drew characters owned by third parties. A pack comes back only under a licence that
 * allows redistribution inside an MIT app, recorded in THIRD-PARTY-NOTICES.md.
 *
 * To add one: drop arrow.png/pointer.png into public/cursors/<id>/ and add an entry here
 * with hotspots normalized to the 32-logical reference (divide a 128px-pack hotspot by 4).
 * No renderer changes needed. An id that leaves this list reads back as the default art
 * through `normalizeCursorThemeId`, so a project saved with it still opens.
 */
export const CURSOR_THEMES: readonly CursorTheme[] = [];

/** All selectable theme ids, including the built-in default. */
export const CURSOR_THEME_IDS: ReadonlySet<string> = new Set([
	DEFAULT_CURSOR_THEME_ID,
	...CURSOR_THEMES.map((theme) => theme.id),
]);

/**
 * Paths the theme picker should show. `pointer` is set only when that artwork
 * differs from `arrow`, so a pack with its own hand is not previewed as arrow-only.
 */
export function themePickerPreviewAssets(theme: CursorTheme | null): {
	arrow: string;
	pointer: string | null;
} {
	if (!theme) {
		const arrow = DEFAULT_CURSOR_SPRITES.arrow.assetPath;
		const pointer = DEFAULT_CURSOR_SPRITES.pointer.assetPath;
		return { arrow, pointer: pointer !== arrow ? pointer : null };
	}
	const arrow = theme.assets.arrow?.assetPath ?? theme.assets.pointer?.assetPath ?? "";
	const pointer = theme.assets.pointer?.assetPath ?? null;
	return { arrow, pointer: pointer && pointer !== arrow ? pointer : null };
}

/** Returns the theme for `id`, or null for the default / unknown ids. */
export function getCursorTheme(id: string | null | undefined): CursorTheme | null {
	if (!id || id === DEFAULT_CURSOR_THEME_ID) {
		return null;
	}
	return CURSOR_THEMES.find((theme) => theme.id === id) ?? null;
}

/**
 * Normalizes a persisted/incoming theme id to a known value, falling back to the
 * default for anything unrecognized.
 */
export function normalizeCursorThemeId(id: unknown): string {
	return typeof id === "string" && CURSOR_THEME_IDS.has(id) ? id : DEFAULT_CURSOR_THEME_ID;
}

/**
 * The full sprite set for a theme: its own art where it has any, the built-in art for
 * every other cursor state.
 *
 * A pack may ship only an arrow and a pointer, but a recording moves through a dozen OS
 * states — text, resize, wait, grab. Serving the theme's arrow for all of them (what the
 * native path used to do) shows a resize handle as an arrow; serving nothing shows a
 * placeholder. Mixing in the built-in art per state keeps the pointer honest about what
 * the user was doing, and a pack that later adds a text.png slots straight in.
 */
export function resolveCursorSprites(
	themeId: string | null | undefined,
	alwaysArrow = false,
): Record<NativeCursorType, CursorSprite> {
	const sprites = { ...DEFAULT_CURSOR_SPRITES };
	for (const [type, asset] of Object.entries(getCursorTheme(themeId)?.assets ?? {})) {
		if (asset.width <= 0 || asset.height <= 0) {
			continue;
		}
		sprites[type as NativeCursorType] = {
			assetPath: asset.assetPath,
			// Theme hotspots are authored against the asset's own 32-logical reference;
			// the contract is a fraction of the image. See CursorSprite.
			hotspotX: asset.hotspotX / asset.width,
			hotspotY: asset.hotspotY / asset.height,
		};
	}
	// "Always use arrow": one consistent pointer for the whole recording, the I-beam and the
	// hand included. Done on the table the compositor reads, so it needs no mode of its own.
	if (alwaysArrow) {
		for (const type of Object.keys(sprites) as NativeCursorType[]) {
			sprites[type] = sprites.arrow;
		}
	}
	return sprites;
}
